Section "InputClass"
	Identifier "SYNA8004:00 06CB:CD8B Touchpad"
	Driver "libinput"
	MatchIsTouchpad "on"
	Option "Tapping" "on"
	Option "NaturalScrolling" "on"
EndSection

Section "InputClass"
	Identifier "ThinkPad Extra Buttons"
	Driver "libinput"
	Option "ClickMethod" "buttonareas"
EndSection
