[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
bold_italic = { family = "CaskaydiaMono Nerd Font" }
size = 9

[colors.primary]
background = '#000000'
foreground = '#ffffff'
